Update deploy_ec2.yml

diff --git a/.github/workflows/deploy_ec2.yml b/.github/workflows/deploy_ec2.yml
--- a/.github/workflows/deploy_ec2.yml
+++ b/.github/workflows/deploy_ec2.yml
@@ -29,4 +29,5 @@ jobs:
       run: terraform init
 
     - name: Deploy EC2
-      run: terraform apply -auto-approve
+      run: |
+        terraform apply -auto-approve || (echo "Error during apply, executing terraform destroy" && terraform destroy -auto-approve && exit 1)
